language: ruby

bundler_args: "--binstubs --standalone --without documentation --path ../bundle"
script: "bundle exec rake test"
rvm:
  - 2.0.0
  - 2.1.5
  - 2.2.0
  - 2.3.1
notifications:
  email: false
